apiVersion: apps/v1
kind: Deployment
metadata:
  name: caption
  labels:
    app: caption
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caption
  template:
    metadata:
      labels:
        app: caption
    spec:
      containers:
        - name: caption
          image: username/caption:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5